#!/usr/bin/env python3

import argparse
import json
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the args")

# Parse the args
args, unknown = parser.parse_known_args()

# Iterate over collections
for collection in args.json["collections"]:
    
    subprocess.run("""
        java -cp anserini.jar io.anserini.index.IndexCollection
            -collection TrecCollection -generator JsoupGenerator
            -threads 1 -index {0}
            -input {1}
            -storePositions -storeDocvectors -storeRawDocs
    """.format(collection["name"], collection["path"]).split())

    subprocess.run("""
        /work/olddog/target/appassembler/bin/nl.ru.convert.Convert
        -index /work/{0}
        -docs docs
        -dict dict
        -terms terms
    """.format(collection["name"]).split())

    subprocess.run('mv dict /tmp/dict'.split())
    subprocess.run('mv terms /tmp/terms'.split())
    subprocess.run('mv docs /tmp/docs'.split())
