#!/bin/bash

echo Downloading anserini.jar
wget -q http://central.maven.org/maven2/io/anserini/anserini/0.4.0/anserini-0.4.0-fatjar.jar -O anserini.jar
git clone https://github.com/chriskamphuis/olddog.git
cd olddog
mvn clean package appassembler:assemble
