#!/usr/bin/env python3

import argparse
import json
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the args")

# Parse the args
args, unknown = parser.parse_known_args()

topic_path = args.json['topic']['path']
out_file_name = args.json['opts']['out_file_name']

mode = ''
try:
    if args.json['opts']['mode'] == 'disjunctive' :
        mode = '--disjunctive'
except:
    pass

# Recreate socketfiles by creating new farm
subprocess.run('monetdbd start /work/mydbfarm'.split())

subprocess.run("""
    python3 /work/olddog/src/main/python/search_collection.py
        --filename {}
        --output /output/{}
        {}
""".format(topic_path, out_file_name, mode).split())
